version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels: ['update: packages 📦']
    reviewers: ['giotramu']
    schedule:
      interval: 'monthly'
      time: '05:00'
      timezone: 'Europe/Rome'