name: Release

on:
  release:
    types:
      - 'created'
    branches:
      - 'stable'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/fermium'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Publish to NPM with the next tag'
        if: 'github.event.release.prerelease'
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Publish to NPM with the latest tag'
        if: '!github.event.release.prerelease'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
